"""패션 카드 오리지널 생성 샷 목록. (id, year, subject)"""

def style(year):
    if year <= 2001:
        cam = ("candid snapshot shot on a cheap disposable film camera or early 1-megapixel digital camera in South Korea, "
               f"{year}. Harsh on-camera flash, mild motion blur, film grain, slightly faded warm colors with a green-yellow fluorescent cast, dark vignetted corners")
    elif year <= 2009:
        cam = ("candid snapshot taken with a cheap compact digital camera or a 2-megapixel camera phone in South Korea, "
               f"{year}. Slight overexposure from on-camera flash, soft focus, low resolution feel, warm slightly green-cast tone, subtle vignetting")
    else:
        cam = ("candid snapshot taken with an early smartphone camera in South Korea, "
               f"{year}. Natural light, slightly noisy shadows, mild JPEG softness, plain unedited colors, no filter look")
    return "STYLE: " + cam + ", 4:3 landscape aspect ratio, looks like a real found photo, not a fashion editorial."

RULES = ("COMPOSITION: main subject within the central 70% of the frame. Keep the bottom-right 15% of the frame clear of important detail (plain ground/wall) for an overlay stamp. "
         "Every person is a completely fictional Korean person who does not resemble any real celebrity or real individual. "
         "No text, no readable letters or Hangul, no brand logos, no watermarks anywhere. Signage in the background must be blurred/unreadable.")

SHOTS = [
    ("1998-fashion-1", 1998, "A Korean teenage boy in extremely baggy wide-leg hip-hop jeans worn low on the hips, hems dragging on wet pavement and frayed, oversized striped t-shirt, walking past a small stationery shop after rain. Full body, low angle emphasising the wide hems."),
    ("1998-fashion-2", 1998, "Close-up of a Korean schoolgirl's wrist and hand resting on a wooden classroom desk, with two or three colorful satin scrunchie hair ties worn on the wrist like bracelets, a pencil case and a paper cup nearby, afternoon window light. No face."),
    ("1999-fashion-1", 1999, "A Korean teenager on a subway platform wearing a small black nylon fanny pack (waist bag) buckled at the front of the waist over a baggy t-shirt and wide jeans, hand resting on the bag, fluorescent platform light, other commuters blurred. Waist-up framing centred on the bag."),
    ("1999-fashion-2", 1999, "A Korean teenage girl (fictional face) looking into a small mirror in her bedroom, her black hair has one bleached blonde highlight streak in the front bangs, wearing a school uniform blouse, pastel bedroom with a CRT TV in the corner, warm lamp light."),
    ("2000-fashion-2", 2000, "Close-up of a Korean teenage boy's hands and collar: a thin silver chain necklace over a black t-shirt and two chunky silver rings on his fingers, resting on a PC bang keyboard, bluish monitor glow. No face."),
    ("2000-fashion-3", 2000, "Back view of a Korean high school boy walking to school on a morning street, a classic boxy dark navy canvas school BACKPACK (two-strap rucksack with a top handle and front zip pocket, no logo) worn on ONE shoulder only, the other strap dangling free, straps extended very long so the backpack hangs down near his hip, school uniform jacket, apartment buildings and a bus in the background."),
    ("2001-fashion-1", 2001, "A Korean teenage boy (fictional face) wearing a soft cotton bucket hat pulled low over his eyebrows, oversized hoodie, standing in front of a brightly lit noraebang entrance at night, neon signs blurred and unreadable, flash lighting on his face."),
    ("2001-fashion-2", 2001, "A Korean teenage boy sitting on concrete apartment stairs wearing khaki cargo hip-hop pants with many bulging pockets, chunky white sneakers, a beeper clipped to a pocket, looking away. Knees-down to waist emphasised, face partly out of frame."),
    ("2002-fashion-1", 2002, "A crowd of Korean people at a downtown plaza at night during the 2002 World Cup street cheering, everyone in plain bright red t-shirts and red devil-horn headbands, some with red bandanas, arms raised, giant screen glow in the background out of focus. Shot from within the crowd, flash lighting, no readable text on any shirt."),
    ("2003-fashion-1", 2003, "A Korean young woman (fictional face) in head-to-toe denim: a cropped light denim jacket over a short cropped top showing the midriff, and low-rise flared jeans with a wide belt, long straight brown hair, posing casually on a Seoul shopping street in daylight."),
    ("2003-fashion-2", 2003, "Two Korean teenagers at a neighbourhood playground both wearing matching velour tracksuit sets (jacket and pants in the same color with white side stripes), one on a swing, late afternoon light, apartment blocks behind. No faces clearly visible."),
    ("2004-fashion-1", 2004, "A Korean high school student walking to school in the morning wearing the school uniform blazer on top but grey tracksuit pants and three-stripe rubber slide sandals with white socks on the bottom, carrying a backpack, school gate blurred in the background. Full body from behind at a slight angle."),
    ("2004-fashion-2", 2004, "Winter morning in front of a Korean school gate with light snow on the ground, close-up of several students' legs: pleated school uniform skirts with black tights and tan sheepskin boots, plus one pair of uniform trousers with the same boots. Legs only, no faces."),
    ("2006-fashion-2", 2006, "A Korean teenage girl (fictional face) downtown on a weekend wearing an oversized long t-shirt that reaches mid-thigh over black leggings and ballet flats, a long fringe, holding a small shopping bag, waiting at a crosswalk, buildings blurred."),
    ("2007-fashion-1", 2007, "A Korean teenage boy sitting on a school bench wearing school uniform trousers rolled up slightly to show bright colorful high-top canvas sneakers laced loosely, one foot propped up, plain design without logos. Low angle focused on the shoes, face out of frame."),
    ("2007-fashion-2", 2007, "Back view of two Korean teenage best friends walking arm in arm on a shopping street wearing identical pastel zip-up hoodies with the hoods up, skinny jeans, a photo sticker booth shop glowing in the background, evening."),
    ("2008-fashion-1", 2008, "A Korean university student (fictional face) on a campus path in autumn wearing an unbuttoned red and navy plaid flannel shirt over a white t-shirt, dark jeans, holding a textbook, ginkgo leaves on the ground, warm afternoon light."),
    ("2008-fashion-2", 2008, "A Korean teenage girl (fictional face) at a cafe table wearing thick black horn-rimmed plastic glasses that obviously have no lenses, smiling, straight bangs, a small cup of drink and a flip phone on the table, warm interior light."),
    ("2009-fashion-2", 2009, "A Korean high school girl seen from behind walking home, a red plaid flannel shirt tied by its sleeves around the waist of her school uniform skirt, backpack, tree-lined street, afternoon. No face."),
    ("2010-fashion-1", 2010, "Korean high school students waiting at a bus stop on a cold morning, several of them wearing puffy black padded winter jackets over school uniforms, breath visible, one holding a paper cup, no logos on the jackets, grey winter light."),
    ("2010-fashion-2", 2010, "Four Korean friends walking up subway exit stairs seen from behind, all wearing tight skinny jeans in slightly different shades of blue and black, sneakers and flats, casual jackets, daylight at the top of the stairs."),
    ("2011-fashion-1", 2011, "Inside a Korean high school classroom in winter, view from the back: rows of students at desks nearly all wearing identical puffy black padded jackets over uniforms, a few heads down sleeping, heater and chalkboard at the front, no readable writing on the board."),
    ("2011-fashion-2", 2011, "Close-up of a Korean high school girl's legs at the school entrance: pleated uniform skirt, black skinny jeans-style opaque tights, and black flat shoes with the heel backs crushed down and worn like slippers, indoor shoe rack behind. No face."),
    ("2012-fashion-1", 2012, "A Korean teenage boy (fictional face) wearing a flat-brimmed snapback cap with a blank plain front and a shiny sticker still left on the brim, oversized t-shirt, headphones around his neck, in front of a convenience store at night."),
    ("2012-fashion-2", 2012, "A Korean young woman (fictional face) on an autumn street wearing a khaki military-style parka jacket with a fur-trimmed hood and drawstring waist, a grey hoodie layered underneath with the hood out, skinny jeans, holding a takeaway coffee."),
    ("2013-fashion-1", 2013, "Close-up of many students' feet crossing a school crosswalk in the morning, most wearing grey suede retro running sneakers with white soles (plain, no logo), school uniform trousers and skirts, white painted stripes on the road."),
    ("2013-fashion-2", 2013, "A group of Korean university students walking across campus wearing matching varsity baseball jackets with wool bodies and contrasting sleeves in navy and white, the chest and back completely plain with no lettering, spring day, cherry blossoms out of focus."),
    ("2014-fashion-1", 2014, "A Korean teenager (fictional face) taking a mirror selfie in a bedroom wearing an oversized grey crewneck sweatshirt with a large but completely blurred unreadable print across the chest, phone covering part of the face, cluttered desk with a laptop behind."),
    ("2014-fashion-2", 2014, "Low-angle close-up of a Korean teenage boy's legs sitting on a bench: black jogger pants with elasticated cuffs tightly gathered at the ankle, white socks and white sneakers, a backpack on the ground beside him. No face."),
    ("2015-fashion-1", 2015, "Close-up of a Korean student's feet on a subway train floor wearing black and white checkerboard-pattern canvas slip-on shoes without laces, cropped jeans showing the ankles, other passengers' shoes around. No logos, no face."),
    ("2015-fashion-2", 2015, "A Korean teenage girl (fictional face) at a hangang riverside park in summer wearing a navy baseball cap with a plain embroidered emblem that is blurred and unreadable, a white t-shirt, long hair through the cap opening, bicycles behind, golden hour."),
    ("2016-fashion-1", 2016, "Korean students walking to school on a spring morning, most wearing khaki green nylon bomber jackets with orange lining visible at the collar and cuffs, backpacks, school gate ahead. Shot from behind, no faces."),
    ("2016-fashion-2", 2016, "A Korean high school boy sitting on a classroom desk wearing school uniform trousers tailored extremely slim into a skinny fit, ankle showing, white sneakers, shirt untucked, classmates blurred in the background, afternoon light. Face out of frame."),
]

SHOTS += [
    # ---- food ----
    ("1999-food-2", 1999, "Close-up of a Korean kid's hand holding a FROZEN fish-shaped ICE CREAM sandwich: a thin crisp golden wafer shell shaped like a carp with scale pattern, frost on the surface, a bite taken revealing white vanilla ICE CREAM (not bread) with a thin layer of red bean, slightly melting drips, summer heat, in front of an ice cream freezer chest at a small supermarket, plain torn wrapper without printing."),
    ("2001-food-2", 2001, "Close-up of a Korean teenager holding a twisted spiral-shaped strawberry ice pop (red and pink helical twist on a stick) that is starting to melt and drip onto fingers, hot summer afternoon on apartment complex steps, plain wrapper without text."),
    ("2003-food-1", 2003, "Close-up of a Korean student's hand holding a chilled purple grape-flavoured soft drink can with condensation, a few whole peeled grape pulps visible in a small clear cup poured next to it, on a stationery shop counter, afternoon light, the can has no text or logo."),
    ("2006-food-1", 2006, "Korean classroom desk close-up: a hand offering a single small pastel-colored soft chewy candy cube (unwrapped, strawberry pink and grape purple) to a classmate's open palm, a paper stick of the candies partly opened on the desk with a plain wrapper, other kids' hands reaching in, fluorescent light."),
    ("2007-food-1", 2007, "A cheap Korean neighbourhood pizza shop scene: an open plain white cardboard pizza box on a small table with a thin sweet-corn and cheese pizza cut into slices, a bottle of pickles cup and a can of cola beside it, two teenagers' hands grabbing slices, evening fluorescent light, no text on the box."),
    ("2010-food-1", 2010, "Inside a big bright Korean franchise cafe in 2010: a wooden table with a thick waffle topped with whipped cream and ice cream, a large shaved-ice dessert with red beans and fruit, two iced coffees, young women's hands with cameras, warm wood interior with bookshelves blurred, no readable signs."),
    ("2010-food-2", 2010, "Close-up at a Korean street stall at night: a vendor's gloved hand folding a hot round waffle in half over a thick swirl of whipped cream and strawberry jam, handing it wrapped in a paper napkin to a customer, waffle iron and warm bulb light behind, no text."),
    ("2012-food-1", 2012, "Korean teenage boy (fictional face) at a convenience store counter table, eyes watering and face red, mouth open fanning with his hand, in front of a bowl of extremely red fiery stir-fried spicy noodles in a black tray, a carton of milk next to it, friends laughing blurred behind, plain packaging without text."),
    ("2012-food-3", 2012, "A Korean street cup-rice stall near a school: a paper cup filled with white rice topped with spicy stir-fried pork, fried egg and kimchi, held in a student's hand with a plastic spoon, steam rising, stall counter and a big steel pan in the background, evening, no readable signs."),
    ("2013-food-3", 2013, "Close-up of a Korean teenager holding a tall paper cup that has a smaller cup of crispy popcorn chicken stacked on top of a cup of cola with a straw, at a franchise chicken shop counter, plain cups without logos, bright interior light."),
    ("2016-food-3", 2016, "Close-up of an opened plain bag of long colorful gummy worm candies (translucent red, orange, green, yellow, sugar-free glossy) spilled on a school desk, a Korean student's fingers pulling one worm long, textbook and pencil case beside, afternoon classroom light, no text on the bag."),
    # ---- device ----
    ("1998-device-1", 1998, "Close-up of a Korean teenager's hand pulling a small black pager (beeper) with a tiny green LCD from a jeans pocket, digits glowing on the LCD are blurred/unreadable, in front of a public telephone booth on a Seoul street at dusk, flash lighting, plain device without text."),
    ("1999-device-1", 1999, "A Korean teenage boy (fictional face) on a bus, flipping open a small black flip phone with a stubby antenna and a tiny monochrome screen, holding it to his ear and grinning, bus window and evening city lights behind, film snapshot look, no logo on the phone."),
    ("2001-device-1", 2001, "Close-up of a Korean teenager's hands holding a small candy-bar mobile phone with a tiny colour LCD glowing, thumb on the keypad, a beaded phone strap dangling, a PC bang desk with a CRT monitor glow behind, the screen content is unreadable, no logos."),
    ("2003-device-1", 2003, "A Korean high school girl (fictional face) holding a chunky early camera phone at arm's length to take a photo of her friend, the tiny screen showing a blurry image, on a school rooftop in sunlight, uniform, 2003 snapshot look, no logo on the phone."),
    ("2004-device-2", 2004, "Close-up of a Korean teenager's hand snapping shut a silver clamshell flip phone with a small external LCD and antenna nub, finger on the hinge, a beaded strap and a small plush charm attached, on a classroom desk with textbooks, fluorescent light, no logo on the phone."),
    # ---- school ----
    ("1999-school-1", 1999, "Inside a cramped Korean comic-book rental shop (manhwabang) in 1999: floor-to-ceiling shelves of well-worn comic volumes with their spines blurred so no titles are readable, a teenager sitting on a low stool reading under a fluorescent tube, a small instant-noodle cup beside, warm cluttered atmosphere."),
    ("2003-school-1", 2003, "Korean high school classroom during late-night self-study: close-up of a student hiding a small pocket radio in a hoodie sleeve on the desk with one earphone wire running up under the hair, textbook open as cover, desk lamp glow and dark windows behind, no faces clearly visible."),
    ("2004-school-1", 2004, "Close-up of a Korean student's hand pushing a blue 3.5-inch floppy diskette into the A-drive of a beige desktop computer tower in a school computer lab, a CRT monitor with a blurred screen above, a stack of diskettes with handwritten labels that are unreadable beside, fluorescent light."),
    ("2005-school-1", 2005, "Korean classroom scene: a small folded paper note shaped like a heart being passed secretly under the desks between two students' hands, uniform sleeves, the note is plain paper with no readable writing, teacher blurred at the front, warm afternoon light."),
    ("2008-school-1", 2008, "Close-up on a Korean school desk during break: a stack of 500-won and 100-won Korean coins, one coin mid-spin after a student slapped the desk edge with an open palm, several boys' hands and uniform sleeves crowding around, chalk dust and fluorescent light, coins' engravings blurred."),
    ("2009-school-1", 2009, "Korean high school night self-study classroom: view from under the desk showing a student's hands holding a slide phone low on the lap, thumbs tapping a game with the small screen glow lighting the uniform trousers, the screen itself is unreadable, dark room, other students' legs and school bags around."),
    ("2011-school-1", 2011, "Two Korean high school students sitting side by side at a desk during night self-study, each with one earbud of a single pair of white wired earphones, the cord stretched between them, heads slightly tilted together, one writing in a workbook, desk lamps, warm quiet mood, faces partly turned away."),
    ("2013-school-1", 2013, "A Korean middle school retreat (suryeonhoe) campfire night: students in matching camp t-shirts sitting in a big circle on the ground around a tall bonfire in a rural training-camp yard, holding small candles, sparks rising, some wiping tears, dark forested hills behind, no readable text."),
    ("2015-school-1", 2015, "Korean school retreat candle ceremony in a dim auditorium hall: rows of teenagers holding small candles in paper cups, faces softly lit from below, a few crying and hugging, a stage with a bonfire projection blurred, quiet emotional moment, no readable text."),
    ("2016-school-1", 2016, "Interior of a modern Korean study cafe in 2016: rows of individual desks with partition panels, warm LED desk lamps, students in hoodies studying with laptops and thick workbooks, a shelf of free coffee and snacks blurred in the background, clean bright quiet atmosphere, no readable signs."),
]
